client/src/components/ownerSignUp/Modal.jsx

componente creado para consumirse en el form al tocar el boton.

Host crear usuario 

---

api/src/config/config.js

solo cambie algo en mi carpeta config

solo  un cambio en config

---

api/src/middlewares/verifyRecord.ts
api/src/routes/signup.ts

validacion de que un usuario no se registre con el  mismo email o  el mismo name

verificacion del registro de usuario

---

api/index.ts
api/src/models/club.ts
api/src/models/field.ts
api/src/models/user.ts
api/src/routes/index.ts

En teoria no hay conflictos con otros archivos. que trabajo Leo Deberia andar tranqui

Agregue los modelos de club y cancha

---

api/src/controller/UserController.ts
api/src/middlewares/verifyRecord.ts
api/src/routes/index.ts
api/src/routes/signup.ts
api/src/routes/user.ts

cambie la validacion que solo lo haga ppor email y agrego ruta get users para eze

Correji la validacion y agregue ruta get user

---

api/src/config/config.js
api/src/controller/FieldController.ts
api/src/routes/field.ts
api/src/routes/index.ts
api/src/routes/signup.ts

Ruta para traer canchas si le paso el id de un club por query o sino traer todas las canchas de la db.
Ruta para postear tu cancha

Rutas para traer canchas agregadas

---

api/src/controller/ClubController.ts
api/src/controller/UserController.ts
api/src/models/club.ts

Elimine la ruta esa que mandaba todos los email. La modifique por un get que te trae el usuario en cuestion por email.
Agregue los campos latitude y longitude a la tabla de club

Arregle detalles charlados en la reunion de hoy

---

client/package-lock.json
client/package.json
client/src/App.jsx
client/src/components/ClubDetail/ClubDetail.jsx
client/src/components/FieldCalendar/FieldCalendar.jsx
client/src/components/FieldCalendar/fieldCalendar.css

Club detail con field calendar

Club detail

---

api/package.json

"arreglado" el start script. es probable que traiga problemas cuando hagamos deploy.

Updatea package.json npm start script

---

api/src/controller/ClubController.ts

solo cambie el metodo get para que el club  traiga las canchas que tiene

cambios de la ruta club

---

client/src/components/NavBar/NavBar.css
client/src/components/NavBar/NavBar.jsx

creado el componente de navbar

creacion de NavBar

---

api/src/controller/ClubController.ts
api/src/routes/club.ts

Saque las canchas de getClub y las inclui solo cunado trae los detalles  del club

Listo el get a detail

---

api/src/controller/BookingController.ts
api/src/routes/booking.ts

Hecha la ruta para postear reservas

Ruta post reservas hecha

---

api/src/controller/BookingController.ts
api/src/models/user.ts
api/src/routes/booking.ts
api/src/routes/index.ts

ruta del get de bookings
- le saque el password allownull false al model de user

Ruta get bookings y detalles menores

---

api/src/controller/AuthController.ts
client/src/components/OwnerSignUp/OwnerSignUp.jsx

Refactoriza el ownerSignUp
cambiando .create a .findOrCreate, entre otras cosas.

Refactor ownersignup

---

api/src/controller/AuthController.ts

Refactorizo userSignUp en controlador de autenticacion
Cambio .create por .findOrCreate. promesas por async await.

refactoriza userSignUp

---

api/src/models/user.ts

cambie el regex del campo name para que pueda recibir ñ tambien

cambio el regex para que el name reciba ñ

---

api/src/controller/FieldController.ts
api/src/models/field.ts

Me habia olvidado que la ruta de post de canchas acepte la surface

Enum field

---

api/src/controller/ClubController.ts

Cambios en la ruta club para crear las canchas junto  con el club

cambios en la  ruta club

---

client/src/App.jsx
client/src/components/Login/Login.jsx
client/src/components/Login/Modal/Modal.jsx
client/src/components/createClub/CreateClub.jsx
client/src/redux/action/index.js
client/src/redux/reducer/index.jsx

-load user into state when login
-login redirect
-create club debug

login y user a state

---

api/src/models/club.ts

Le saque la validacion alfa al club...es un poco mas libre el nombre del club que el de las personas

Validacion nombre club

---

api/package.json
api/src/config/config.js

Cambio del package.json y el archivo de config para que funcione el deploy en heroku. Deberia estar todo en regla

Settings para deploy

---

client/src/components/Footer/Footer.jsx
client/src/components/Landing/Landing.jsx
client/src/components/NavBar/NavBar.jsx
client/src/components/Slider/Slider.jsx

Arregla algunos errores menores en la landing. Tambien comenta console.log's innesesarios por ahora.

fixea algunos errores menores en la landing. gracias Eze!

---

client/src/components/createClub/FieldForm.jsx

Pequeño arreglo. Al intentar crear cancha con superficie cesped, se rompia el back. El back esperaba "cesped" y recibia "pasto".
Cambie pasto x cesped, ya que el selector en realidad decia "Cesped"

small fix at fieldForm, pasto -> cesped.

---

api/src/controller/AuthController.ts

pequeño error que crashea el back cuando intento hacer signup con body incompleto o nulo.

fixea crash cuando se intenta signup con body incompleto o nulo

---

client/src/App.jsx
client/src/components/ClubDetail/ClubDetail.jsx

arreglé las rutas en App.js y conecté la lista de clubes con la pagina detalle

App routes and clubdetail

---

api/index.ts
api/package.json
api/src/config/email.js
api/src/controller/AuthController.ts
api/src/models/user.ts
api/src/routes/signup.ts

implementacion nodemailer, hacer npm  i en el back

implementacion de nodemailer

---

client/src/components/Landing/Landing.jsx
client/src/components/Landing/Landing.module.css

Cambiar hero
Poner frase motivadora

cambiohero

---

client/src/components/ClubDetail/ClubDetail.jsx

cambié el mapa de club detail por el de google

clubDetail with google map

---

api/src/routes/signup.ts

rutas sin implementar para que comenzar en el front (EZE)

rutas para trabajarlas en front

---

api/index.ts
api/src/config/email.js
api/src/controller/AuthController.ts
api/src/routes/signup.ts

Trabajando rutas

---

api/index.ts
client/src/App.jsx
client/src/components/CardClub/CardClub.jsx
client/src/components/ClubDetail/ClubDetail.jsx
client/src/components/ListClubs/ListClubs.jsx

mejora la url de los clubes. arregla los warnings en front y pongo force en false.

Url de clubes y warnings.

---

client/src/components/Email/Email.jsx

cambioMail

---

api/package.json
api/src/controller/CheckoutController.ts

corregido el nombre del archivo que rompia heroku

Deploy debug

---

client/src/components/OwnerSignUp/OwnerSignUp.jsx
client/src/components/UserSignUp/UserSignUp.jsx

Faxeado el bug donde si se ponían diferentes contraseñas dejaba crear la cuenta igual.

fixeado el bug de las passwords

---

client/src/components/createClub/CreateClub.jsx

added google map to create club

added google map to create club

---

api/index.ts
api/src/controller/CheckoutController.ts
api/src/controller/ClubController.ts
client/src/App.jsx
client/src/components/Checkout/Checkout.jsx

cree nuevo componente y ruta para manejar el feedback de Mercadopago

checkout back url for mercadopago

---

api/src/controller/UserController.ts
api/src/routes/user.ts

put y delete  en user

---

client/src/components/Checkout/Checkout.jsx
client/src/components/ClubDetail/ClubDetail.jsx

completé el componente checkout para cierra el modal de mercadopago

checkout logic

---

client/src/components/Map/Map.jsx

aaaaaaaaalfin se arreglo esa bosta

arregla el crash cuando volvias a la landing

---

client/src/components/Order/OrderPrice.jsx
client/src/redux/action/index.js
client/src/redux/reducer/index.jsx

terminado el filtro por ciudad, queda  ver si se encuentra algún bug

Filtro localidad

---

client/src/components/createClub/CreateClub.jsx
client/src/components/createClub/FieldForm.jsx
client/src/components/createClub/createClub.css

Agregué algunos estilos en createClub

styled create club

---

api/src/controller/ClubController.ts

club address "num" attribute to integer

fixed num attribute

---

api/src/controller/UserController.ts
client/src/components/Dashboard/Admin.jsx

agregue async await en los dispatch de update y delete de admin por que refrescaba la pagina pero nunca dispachaba la accion

arregle el dash de admin

---

client/src/components/Dashboard/Owner.jsx

puse el fieldCalendar en el owner dashboard, por ahora sin funcionalidad

feature field calendar to owner dashboard

---

client/src/components/Dashboard/Owner.jsx

Dashboard calendar funcionando

feature: owner can block dates

---

api/src/controller/UserController.ts
api/src/models/user.ts

Agregue el campo autherized (False por default) para autorizar al owner a crear clubes
Y ahora el get all users de admin trae ese campo tambien

Agregado el campo authorized

---

api/src/config/email.js
api/src/controller/BookingController.ts
api/src/routes/booking.ts

todavia le  falta a la ruta nueva

hice algunos cambios , la ruta del  plus necesita un poco mas

---

api/src/config/email.js
api/src/controller/BookingController.ts
api/src/routes/booking.ts

solo agregue un par de cosas al tema de   las invitaciones no agregue middlewares  por que nico ya arreglo lo  de  las reservas

solo  agregue un par de cositas

---

api/utils.js
client/src/components/Dashboard/Admin.jsx

Agregada la logica para autorizar owner y corregido las location de tierra del fuego

Agregada logica Autorizacion

---

client/src/components/ListClubs/ListClubs.jsx

fixed map filter

---

api/src/controller/UserController.ts

Antes no se borraban los clubes del  owner eliminado, ahora ya se  borra

Listo se borran todos  los clubes relacionados al owner

---

api/src/models/booking.ts
api/src/models/club.ts

Agregue la columna totalRantings a Club, modifique la de score para que sea un float
Agregue un booleano a booxing que por default es false que se cambiaria a true cuando elijan el score

corregidos los modelos de club y booking

---

client/src/components/createClub/CreateClub.jsx

-componente solo para owner
-cambia score a number

Protected create

---

client/src/components/ClubDetail/ClubDetail.jsx
client/src/components/ClubDetail/FieldCalendar/FieldCalendar.jsx
client/src/components/Dashboard/Owner.jsx

cambié la tabla de reservas por un div con detalles de la reserva que se clickea en el calendario

improved owner dashboard UX

---

api/src/controller/ClubController.ts
client/src/components/Dashboard/ModalEditarClub/Modal.jsx

corrigiendo errores

---

client/src/components/createClub/CreateClub.jsx
client/src/components/createClub/validation.js

arreglé la validación de CreateClub

fix create club validation

---

api/src/controller/BookingController.ts

solo cambie el  post de booking

---

api/src/controller/BookingController.ts
client/src/components/CardClub/CardClub.jsx
client/src/components/Dashboard/User.jsx
client/src/components/ListClubs/ListClubs.jsx

score hecho

---

client/src/components/Landing/Landing.jsx
client/src/components/ListClubs/ListClubs.jsx
client/src/components/NavBar/NavBar.jsx
client/src/redux/reducer/index.jsx

cambios en la barra de busqueda y data list agregada

Actualizamos la barra de busqueda

---

client/src/components/createClub/CreateClub.jsx

agregué validación al mapa de create club

fix map validation on create club

---

client/src/components/Dashboard/User.jsx

saqué el botón de refresh de user dashboard

no refresh button on user dash

---

client/src/components/Map/Map.jsx

cargue las cities en el select del  mapa

ciudades cargadas en el select
